# Deployment da aplicação php
# backend

apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: szalbuque/cadastro-app-php:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80

